/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Luiz
 */
public class Fabricante extends javax.swing.JInternalFrame {

    /**
     * Creates new form Factory
     */
    public Fabricante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelFabricante = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCodigoFabricante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNomeFabricante = new javax.swing.JTextField();
        jPanelDadosFabricante = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDadosFabricante = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonAdicionarFabricante = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButtonSalvarFabricante = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButtonEXcluirFabricante = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButtonTransferir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(508, 508));
        setMinimumSize(new java.awt.Dimension(508, 508));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 480));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fabricante.png"))); // NOI18N
        jLabel5.setText("Fabricante");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 190, 50);

        jPanelFabricante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fabricante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanelFabricante.setLayout(null);

        jLabel6.setText("Código:");
        jPanelFabricante.add(jLabel6);
        jLabel6.setBounds(17, 21, 50, 16);

        jTextFieldCodigoFabricante.setBackground(new java.awt.Color(238, 238, 238));
        jTextFieldCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldCodigoFabricante.setEnabled(false);
        jPanelFabricante.add(jTextFieldCodigoFabricante);
        jTextFieldCodigoFabricante.setBounds(30, 40, 140, 30);

        jLabel7.setText("Nome:");
        jPanelFabricante.add(jLabel7);
        jLabel7.setBounds(20, 80, 36, 16);

        jTextFieldNomeFabricante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanelFabricante.add(jTextFieldNomeFabricante);
        jTextFieldNomeFabricante.setBounds(30, 100, 440, 30);

        jPanel1.add(jPanelFabricante);
        jPanelFabricante.setBounds(10, 70, 480, 150);

        jPanelDadosFabricante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanelDadosFabricante.setLayout(null);

        jTableDadosFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDadosFabricante.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTableDadosFabricante);

        jPanelDadosFabricante.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 460, 210);

        jPanel1.add(jPanelDadosFabricante);
        jPanelDadosFabricante.setBounds(10, 230, 480, 240);

        jToolBar2.setFloatable(false);
        jToolBar2.setBorderPainted(false);
        jToolBar2.setOpaque(false);
        jToolBar2.add(jSeparator5);

        jButtonAdicionarFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add32x32.png"))); // NOI18N
        jButtonAdicionarFabricante.setToolTipText("Adicionar");
        jButtonAdicionarFabricante.setBorderPainted(false);
        jButtonAdicionarFabricante.setFocusable(false);
        jButtonAdicionarFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdicionarFabricante.setOpaque(false);
        jButtonAdicionarFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonAdicionarFabricante);
        jToolBar2.add(jSeparator6);

        jButtonSalvarFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar32x32.png"))); // NOI18N
        jButtonSalvarFabricante.setToolTipText("Salvar");
        jButtonSalvarFabricante.setBorderPainted(false);
        jButtonSalvarFabricante.setFocusable(false);
        jButtonSalvarFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvarFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonSalvarFabricante);
        jToolBar2.add(jSeparator7);

        jButtonEXcluirFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagar32x32.png"))); // NOI18N
        jButtonEXcluirFabricante.setToolTipText("Excluir");
        jButtonEXcluirFabricante.setBorderPainted(false);
        jButtonEXcluirFabricante.setFocusable(false);
        jButtonEXcluirFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEXcluirFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonEXcluirFabricante);
        jToolBar2.add(jSeparator8);

        jButtonTransferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jButtonTransferir.setText("Transferir");
        jButtonTransferir.setToolTipText("Transferir");
        jButtonTransferir.setBorderPainted(false);
        jButtonTransferir.setFocusable(false);
        jButtonTransferir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonTransferir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonTransferir);

        jPanel1.add(jToolBar2);
        jToolBar2.setBounds(210, 30, 280, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarFabricante;
    private javax.swing.JButton jButtonEXcluirFabricante;
    private javax.swing.JButton jButtonSalvarFabricante;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDadosFabricante;
    private javax.swing.JPanel jPanelFabricante;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTable jTableDadosFabricante;
    private javax.swing.JTextField jTextFieldCodigoFabricante;
    private javax.swing.JTextField jTextFieldNomeFabricante;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
