package view;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Principal extends javax.swing.JFrame {

    private String usuarioLogado;
    private String nivelAcesso;

    public static boolean verificaTelaUsuario;
    public static boolean verificaTelaProduto;

    public static void setVerificaTelaUsuario(boolean verificaTelaUsuario) {
        Principal.verificaTelaUsuario = verificaTelaUsuario;
    }

    public static void setVerificaTelaProduto(boolean verificaTelaProduto) {
        Principal.verificaTelaProduto = verificaTelaProduto;
    }

    private Principal() {

    }

    public String getUsuarioLogado() {
        return usuarioLogado;
    }

    public void setUsuarioLogado(String usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }

    public String getNivelAcesso() {
        return nivelAcesso;
    }

    public void setNivelAcesso(String nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }

    /**
     * Creates new form Principal
     */
    public Principal(String usuarioLogado, String nivelAcesso) {

        this.usuarioLogado = usuarioLogado;
        this.nivelAcesso = nivelAcesso;

        initComponents();

        ActionListener tmrHoraAction = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat minhaData
                        = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
                lblHora.setText(minhaData.format(new Date()));

            }
        };

        Timer tmrHora = new Timer(1000, tmrHoraAction);
        tmrHora.start();
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage(getClass().getResource("Embed48x48.png")));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        lblMostraUsuarioLogado.setText(usuarioLogado);

        verificaNivel(nivelAcesso);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBarraInferior = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        lblUsuarioLogado = new javax.swing.JLabel();
        lblMostraUsuarioLogado = new javax.swing.JLabel();
        toolBarPrincipal = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonProduto = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonEstoque = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonSair = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        subMnuSair = new javax.swing.JMenuItem();
        mnuManutencao = new javax.swing.JMenu();
        subMnuBackup = new javax.swing.JMenuItem();
        subMnuConfiguracao = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlterarSenha = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();
        subMnuAjuda = new javax.swing.JMenuItem();
        subMnuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EmbedStock - Módulo Desktop");
        setName("EmbedStock - Módulo Desktop"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelBarraInferior.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledToolBarBorderBackground"));
        jPanelBarraInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Data/Hota");

        lblUsuarioLogado.setText("Usuário:");

        lblMostraUsuarioLogado.setForeground(java.awt.Color.red);
        lblMostraUsuarioLogado.setText("luizfs");

        javax.swing.GroupLayout jPanelBarraInferiorLayout = new javax.swing.GroupLayout(jPanelBarraInferior);
        jPanelBarraInferior.setLayout(jPanelBarraInferiorLayout);
        jPanelBarraInferiorLayout.setHorizontalGroup(
            jPanelBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarraInferiorLayout.createSequentialGroup()
                .addGap(0, 519, Short.MAX_VALUE)
                .addComponent(lblUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostraUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBarraInferiorLayout.setVerticalGroup(
            jPanelBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraInferiorLayout.createSequentialGroup()
                .addGroup(jPanelBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMostraUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        toolBarPrincipal.setFloatable(false);
        toolBarPrincipal.setRollover(true);
        toolBarPrincipal.setFocusable(false);
        toolBarPrincipal.add(jSeparator1);

        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jButtonUsuario.setToolTipText("Cadastro de Usuários");
        jButtonUsuario.setBorder(null);
        jButtonUsuario.setEnabled(false);
        jButtonUsuario.setFocusPainted(false);
        jButtonUsuario.setFocusable(false);
        jButtonUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuario.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonUsuario.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonUsuario.setOpaque(false);
        jButtonUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        toolBarPrincipal.add(jButtonUsuario);
        toolBarPrincipal.add(jSeparator2);

        jButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto48x48.png"))); // NOI18N
        jButtonProduto.setToolTipText("Cadastro de Produtos");
        jButtonProduto.setBorder(null);
        jButtonProduto.setEnabled(false);
        jButtonProduto.setFocusPainted(false);
        jButtonProduto.setFocusable(false);
        jButtonProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProduto.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonProduto.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonProduto.setOpaque(false);
        jButtonProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });
        toolBarPrincipal.add(jButtonProduto);
        toolBarPrincipal.add(jSeparator4);

        jButtonEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque48x48.png"))); // NOI18N
        jButtonEstoque.setToolTipText("Controle de Estoque");
        jButtonEstoque.setBorder(null);
        jButtonEstoque.setEnabled(false);
        jButtonEstoque.setFocusPainted(false);
        jButtonEstoque.setFocusable(false);
        jButtonEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEstoque.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonEstoque.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonEstoque.setOpaque(false);
        jButtonEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarPrincipal.add(jButtonEstoque);
        toolBarPrincipal.add(jSeparator3);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door48x48.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorder(null);
        jButtonSair.setFocusPainted(false);
        jButtonSair.setFocusable(false);
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setMaximumSize(new java.awt.Dimension(60, 60));
        jButtonSair.setMinimumSize(new java.awt.Dimension(60, 60));
        jButtonSair.setOpaque(false);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        toolBarPrincipal.add(jButtonSair);

        jDesktopPane1.setBackground(java.awt.Color.gray);
        jDesktopPane1.setAutoscrolls(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        mnuPrincipal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        mnuArquivo.setMnemonic('A');
        mnuArquivo.setText("Arquivo");

        subMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door16x16.png"))); // NOI18N
        subMnuSair.setToolTipText("");
        subMnuSair.setLabel("Sair");
        subMnuSair.setName(""); // NOI18N
        subMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMnuSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(subMnuSair);

        mnuPrincipal.add(mnuArquivo);

        mnuManutencao.setMnemonic('M');
        mnuManutencao.setText("Manutenção");

        subMnuBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backup.png"))); // NOI18N
        subMnuBackup.setText("Backup");
        subMnuBackup.setEnabled(false);
        mnuManutencao.add(subMnuBackup);

        subMnuConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N
        subMnuConfiguracao.setText("Configurações");
        subMnuConfiguracao.setToolTipText("");
        subMnuConfiguracao.setEnabled(false);
        mnuManutencao.add(subMnuConfiguracao);
        mnuManutencao.add(jSeparator5);

        jMenuItemAlterarSenha.setText("Alterar Senha");
        mnuManutencao.add(jMenuItemAlterarSenha);

        mnuPrincipal.add(mnuManutencao);

        mnuSobre.setMnemonic('S');
        mnuSobre.setText("Sobre");

        subMnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajuda.png"))); // NOI18N
        subMnuAjuda.setText("Ajuda");
        mnuSobre.add(subMnuAjuda);

        subMnuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        subMnuInfo.setText("Info");
        mnuSobre.add(subMnuInfo);

        mnuPrincipal.add(mnuSobre);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBarraInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBarraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Object[] options = {"Sim", "Não"};

        if (JOptionPane.showOptionDialog(this, "Deseja Sair?", "Atenção",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null,
                options, options[1]) == JOptionPane.YES_OPTION) {

            dispose();

        }

    }//GEN-LAST:event_formWindowClosing

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        formWindowClosing(null);

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void subMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMnuSairActionPerformed

        formWindowClosing(null);

    }//GEN-LAST:event_subMnuSairActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed

        if (verificaTelaUsuario == false) {
            
            Usuario telaUsuario = new Usuario();
            jDesktopPane1.remove(telaUsuario);
            jDesktopPane1.add(telaUsuario);
            telaUsuario.setVisible(true);

        }
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed

        if (verificaTelaProduto == false) {

            Produto telaProduto = new Produto();
            jDesktopPane1.remove(telaProduto);
            jDesktopPane1.add(telaProduto);
            telaProduto.setVisible(true);

        }

    }//GEN-LAST:event_jButtonProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    private void verificaNivel(String niveString) {

        switch (niveString) {

            case "1":

                jButtonUsuario.setEnabled(true);
                jButtonProduto.setEnabled(true);
                jButtonEstoque.setEnabled(true);
                subMnuBackup.setEnabled(true);
                subMnuConfiguracao.setEnabled(true);
                break;
            case "2":

                jButtonProduto.setEnabled(true);
                jButtonEstoque.setEnabled(true);
                break;

            default:

                JOptionPane.showMessageDialog(this, "Nível de Acesso não reconhecido",
                        "Nível Acesso", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                break;

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstoque;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItemAlterarSenha;
    private javax.swing.JPanel jPanelBarraInferior;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMostraUsuarioLogado;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuManutencao;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuSobre;
    private javax.swing.JMenuItem subMnuAjuda;
    private javax.swing.JMenuItem subMnuBackup;
    private javax.swing.JMenuItem subMnuConfiguracao;
    private javax.swing.JMenuItem subMnuInfo;
    private javax.swing.JMenuItem subMnuSair;
    private javax.swing.JToolBar toolBarPrincipal;
    // End of variables declaration//GEN-END:variables
}
