package view;


public class Produto extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabelTituloProduto = new javax.swing.JLabel();
        jPanelProduto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelImagemProduto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxProdutoAtivo = new javax.swing.JCheckBox();
        jComboBoxFabricante = new javax.swing.JComboBox<>();
        jTextFieldCodigoProduto = new javax.swing.JTextField();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jTextFieldDescricaoProduto = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonFabricante = new javax.swing.JButton();
        jPanelDadosProduto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosProduto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonAdicionarProduto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonConsultarProduto = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonSalvarProduto = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonFechar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(930, 700));
        setPreferredSize(new java.awt.Dimension(930, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelTituloProduto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto48x48.png"))); // NOI18N
        jLabelTituloProduto.setText("Cadastro de Produto");
        getContentPane().add(jLabelTituloProduto);
        jLabelTituloProduto.setBounds(12, 12, 240, 46);

        jPanelProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanelProduto.setName(""); // NOI18N
        jPanelProduto.setLayout(null);

        jLabel2.setText("Código:");
        jPanelProduto.add(jLabel2);
        jLabel2.setBounds(250, 30, 50, 16);

        jLabel4.setText("Descrição:");
        jPanelProduto.add(jLabel4);
        jLabel4.setBounds(250, 90, 70, 16);

        jLabel5.setText("Código Barras:");
        jPanelProduto.add(jLabel5);
        jLabel5.setBounds(480, 30, 90, 16);

        jLabelImagemProduto.setBackground(java.awt.Color.lightGray);
        jLabelImagemProduto.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));
        jLabelImagemProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagemProduto.setText("Imagem");
        jLabelImagemProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelImagemProduto.setOpaque(true);
        jPanelProduto.add(jLabelImagemProduto);
        jLabelImagemProduto.setBounds(20, 30, 170, 160);

        jLabel7.setText("Fabricante:");
        jPanelProduto.add(jLabel7);
        jLabel7.setBounds(250, 150, 70, 16);

        jCheckBoxProdutoAtivo.setText("Ativo:");
        jPanelProduto.add(jCheckBoxProdutoAtivo);
        jCheckBoxProdutoAtivo.setBounds(760, 170, 60, 24);

        jComboBoxFabricante.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxFabricante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FabricanteA", "Fabricante B", "Fabricante C" }));
        jPanelProduto.add(jComboBoxFabricante);
        jComboBoxFabricante.setBounds(260, 170, 390, 30);

        jTextFieldCodigoProduto.setBackground(new java.awt.Color(238, 238, 238));
        jTextFieldCodigoProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldCodigoProduto.setEnabled(false);
        jPanelProduto.add(jTextFieldCodigoProduto);
        jTextFieldCodigoProduto.setBounds(260, 50, 190, 30);

        jTextFieldCodigoBarras.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanelProduto.add(jTextFieldCodigoBarras);
        jTextFieldCodigoBarras.setBounds(490, 50, 330, 30);

        jTextFieldDescricaoProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanelProduto.add(jTextFieldDescricaoProduto);
        jTextFieldDescricaoProduto.setBounds(260, 110, 560, 30);

        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        jButtonFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fabricante32x32.png"))); // NOI18N
        jButtonFabricante.setToolTipText("Inserir Novo Fabricante");
        jButtonFabricante.setBorderPainted(false);
        jButtonFabricante.setFocusable(false);
        jButtonFabricante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFabricante.setOpaque(false);
        jButtonFabricante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFabricanteActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonFabricante);

        jPanelProduto.add(jToolBar2);
        jToolBar2.setBounds(660, 160, 40, 40);

        getContentPane().add(jPanelProduto);
        jPanelProduto.setBounds(12, 66, 830, 213);

        jPanelDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jTableDadosProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableDadosProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Fabricante", "Código_Barras", "ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDadosProduto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableDadosProduto.setColumnSelectionAllowed(true);
        jTableDadosProduto.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTableDadosProdutoHierarchyChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosProduto);
        jTableDadosProduto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableDadosProduto.getColumnModel().getColumnCount() > 0) {
            jTableDadosProduto.getColumnModel().getColumn(0).setResizable(false);
            jTableDadosProduto.getColumnModel().getColumn(0).setPreferredWidth(180);
            jTableDadosProduto.getColumnModel().getColumn(1).setPreferredWidth(280);
            jTableDadosProduto.getColumnModel().getColumn(2).setResizable(false);
            jTableDadosProduto.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTableDadosProduto.getColumnModel().getColumn(3).setResizable(false);
            jTableDadosProduto.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableDadosProduto.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanelDadosProdutoLayout = new javax.swing.GroupLayout(jPanelDadosProduto);
        jPanelDadosProduto.setLayout(jPanelDadosProdutoLayout);
        jPanelDadosProdutoLayout.setHorizontalGroup(
            jPanelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosProdutoLayout.setVerticalGroup(
            jPanelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanelDadosProduto);
        jPanelDadosProduto.setBounds(12, 305, 900, 360);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setOpaque(false);
        jToolBar1.setRequestFocusEnabled(false);
        jToolBar1.add(jSeparator1);

        jButtonAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add32x32.png"))); // NOI18N
        jButtonAdicionarProduto.setToolTipText("Adicionar");
        jButtonAdicionarProduto.setBorderPainted(false);
        jButtonAdicionarProduto.setFocusable(false);
        jButtonAdicionarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdicionarProduto.setOpaque(false);
        jButtonAdicionarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAdicionarProduto);
        jToolBar1.add(jSeparator2);

        jButtonConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procurar32x32.png"))); // NOI18N
        jButtonConsultarProduto.setToolTipText("Procurar");
        jButtonConsultarProduto.setBorderPainted(false);
        jButtonConsultarProduto.setFocusable(false);
        jButtonConsultarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultarProduto.setOpaque(false);
        jButtonConsultarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonConsultarProduto);
        jToolBar1.add(jSeparator5);

        jButtonSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar32x32.png"))); // NOI18N
        jButtonSalvarProduto.setToolTipText("Salvar");
        jButtonSalvarProduto.setBorderPainted(false);
        jButtonSalvarProduto.setFocusable(false);
        jButtonSalvarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvarProduto.setOpaque(false);
        jButtonSalvarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonSalvarProduto);
        jToolBar1.add(jSeparator4);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit32x32.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.setBorderPainted(false);
        jButtonFechar.setFocusable(false);
        jButtonFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFechar.setOpaque(false);
        jButtonFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonFechar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(590, 20, 252, 48);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDadosProdutoHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTableDadosProdutoHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDadosProdutoHierarchyChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        Principal.setVerificaTelaProduto(true);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        Principal.setVerificaTelaProduto(false);
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButtonFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFabricanteActionPerformed
        
        TesteForm form = new TesteForm(null, true);
        
        form.setVisible(true);
           
        
    }//GEN-LAST:event_jButtonFabricanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarProduto;
    private javax.swing.JButton jButtonConsultarProduto;
    private javax.swing.JButton jButtonFabricante;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvarProduto;
    private javax.swing.JCheckBox jCheckBoxProdutoAtivo;
    private javax.swing.JComboBox<String> jComboBoxFabricante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImagemProduto;
    private javax.swing.JLabel jLabelTituloProduto;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDadosProduto;
    private javax.swing.JPanel jPanelProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTableDadosProduto;
    private javax.swing.JTextField jTextFieldCodigoBarras;
    private javax.swing.JTextField jTextFieldCodigoProduto;
    private javax.swing.JTextField jTextFieldDescricaoProduto;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
